// src/components/register/Register.vue
<template>
  <form @submit.prevent="register"
        class="position-absolute top-50 start-50 translate-middle w-50 p-5 border border-white rounded">
    <div class="input-data">
      <div class="form-group">
        <label class="mt-3" for="email-input">Email</label>
        <input id="email-input" name="email" :class="{ 'is-invalid': v$.email.$error }" v-model.trim="v$.email.$model"
               class="login-input form-control"
               type="text" autocomplete="off">
        <div class="invalid-feedback" v-for="error in v$.email.$errors" :key="error">
          {{ error.$message }}
        </div>
      </div>
      <div class="form-group">
        <label class="mt-3" for="username-input">Username</label>
        <input id="username-input" name="username"
               :class="{'login-input form-control': true, 'is-invalid': v$.username.$error}"
               type="text" autocomplete="off" v-model.trim="v$.username.$model">
        <div class="invalid-feedback" v-for="error in v$.username.$errors" :key="error">
          {{ error.$message }}
        </div>
      </div>
      <div class="form-group">
        <label class="mt-3" for="password-input">Password</label>
        <input id="password-input" name="password"
               :class="{'login-input form-control': true, 'is-invalid': v$.password.$error}"
               type="password" v-model.trim="v$.password.$model">
        <div class="invalid-feedback" v-for="error in v$.password.$errors" :key="error">
          {{ error.$message }}
        </div>
      </div>
    </div>
    <div class="link-div mt-3 d-flex flex-column">
      <p>Already have an account?
        <router-link :to="{name: 'Login'}">Log in</router-link>
      </p>
      <button class="btn btn-success w-50 align-self-center" :disabled="v$.$invalid">Register</button>
      <span v-for="message in messages" :key="message" class="text-danger align-self-center">{{ message }}</span>
    </div>
  </form>
</template>

<script>
import {register} from "/src/api/auth";
import useVuelidate from '@vuelidate/core'
import {registrationSchema} from "../../utils/validation/auth";


export default {
  setup: () => {
    return {v$: useVuelidate()}
  },
  name: "Register",
  data: () => ({
    email: "",
    username: "",
    password: "",
    messages: []
  }),
  validations: () => (registrationSchema),
  methods: {
    async register() {
      const data = JSON.stringify({
        email: this.email,
        username: this.username,
        password: this.password
      });
      try {
        await register(data);
        this.$toast.info("<h3>We sent confirmation link to your email. Please, check your inbox.</h3>", {
          duration: 0
        });
        await this.$router.push({name: "Home"});
      } catch (error) {
        if (error.status === 400) {
          this.messages = error.data.slice();
        } else {
          this.messages = ["Something went wrong"];
        }
      }
    }
  }
}
</script>

// src/components/register/Register.jsx
import {Link, useNavigate} from "react-router-dom";
import {route} from "../../routes";
import {registrationSchema} from "../../utils/validation/auth";
import {useState} from "react";
import {register} from "../../api/auth";
import {useToasts} from "react-toast-notifications";
import {Formik} from "formik";
import Input from "../form/Input";


const Register = () => {

    const initialData = {
        email: "",
        username: "",
        password: ""
    };

    const [messages, setMessages] = useState([]);

    const {addToast} = useToasts();

    const navigate = useNavigate();

    const submit = async (values) => {
        try {
            await register(values);
            addToast("We sent confirmation link to your email. Please, check your inbox.", {
                appearance: "info",
                placement: "bottom-right",
                autoDismiss: false
            });
            navigate(route("home"));
        } catch (error) {
            if (error.status === 400) {
                setMessages(error.data.slice());
            } else {
                setMessages(["Something went wrong"]);
            }
        }
    }

    return (
        <Formik initialValues={initialData} onSubmit={submit} validationSchema={registrationSchema}>
            {({
                  errors,
                  touched,
                  handleChange,
                  handleBlur,
                  handleSubmit,
                  isSubmitting
              }) => (
                <form onSubmit={handleSubmit}
                      className="position-absolute top-50 start-50 translate-middle w-50 p-5 border border-white rounded">
                    <div className="input-data">
                        <Input
                            field="email"
                            errors={errors.email}
                            touched={touched.email}
                            events={{
                                handleBlur,
                                handleChange
                            }}
                        />
                        <Input
                            field="username"
                            errors={errors.username}
                            touched={touched.username}
                            events={{
                                handleBlur,
                                handleChange
                            }}
                        />
                        <Input
                            field="password"
                            errors={errors.password}
                            touched={touched.password}
                            events={{
                                handleBlur,
                                handleChange
                            }}
                        />
                    </div>
                    <div className="link-div mt-3 d-flex flex-column">
                        <p>
                            Already have an account?
                            <Link to={route("login")}>Log in</Link>
                        </p>
                        <button className="btn btn-success w-50 align-self-center" type={"submit"}
                                disabled={isSubmitting}>Register
                        </button>
                        {messages.map(message =>
                            <span className="text-danger align-self-center" key={message}>
                                {message}
                            </span>
                        )}
                    </div>
                </form>
            )}
        </Formik>
    );
}

export default Register;
