// src/components/login/Login.jsx
import {useState} from "react";
import {Link, useNavigate} from "react-router-dom";
import {login} from "../../api/auth";
import {route} from "../../routes";
import {Formik} from "formik";
import {loginSchema} from "../../utils/validation/auth";
import Input from "../form/Input";
import {useCookies} from "react-cookie";

const Login = () => {

    const initialData = {
        username: "",
        password: ""
    };

    const [cookies, setCookie] = useCookies();

    const [message, setMessage] = useState("");

    const navigate = useNavigate();

    const submit = async (values) => {
        try {
            const response = await login(values);
            setCookie("token", response.token);
            navigate(route("home"));
        } catch (error) {
            if (error.status === 401) {
                setMessage("Incorrect username or password");
            } else {
                setMessage("Something went wrong");
            }
        }
    }

    return (
        <Formik initialValues={initialData} onSubmit={submit} validationSchema={loginSchema}>
            {({
                  errors,
                  touched,
                  handleChange,
                  handleBlur,
                  handleSubmit,
                  isSubmitting
              }) => (
                <form onSubmit={handleSubmit}
                      className="position-absolute top-50 start-50 translate-middle w-50 p-5 border border-white rounded">
                    <div className="input-data">
                        <Input
                            field="username"
                            errors={errors.username}
                            touched={touched.username}
                            events={{
                                handleSubmit,
                                handleBlur,
                                handleChange
                            }}
                        />
                        <Input
                            field="password"
                            errors={errors.password}
                            touched={touched.password}
                            events={{
                                handleSubmit,
                                handleBlur,
                                handleChange
                            }}
                        />
                    </div>
                    <div className="link-div mt-3 d-flex flex-column">
                        <p>
                            No account yet?
                            <Link to={route("register")}>Register</Link>
                        </p>
                        <button className="btn btn-success w-50 align-self-center" type={"submit"}
                                disabled={isSubmitting}>Login
                        </button>
                        <span className="text-danger align-self-center">
                                {message}
                        </span>
                    </div>
                </form>
            )}
        </Formik>
    );
};

export default Login;

// src/components/login/Login.vue
<template>
  <form @submit.prevent="login"
        class="position-absolute top-50 start-50 translate-middle w-50 p-5 border border-white rounded">
    <div class="input-data">
      <div class="form-group">
        <label class="mt-3" for="username-input">Username</label>
        <input id="username-input" name="username"
               :class="{'login-input form-control': true, 'is-invalid': v$.username.$error}"
               type="text" autocomplete="off" v-model.trim="v$.username.$model">
        <div class="invalid-feedback" v-for="error in v$.username.$errors" :key="error">
          {{ error.$message }}
        </div>
      </div>
      <div class="form-group">
        <label class="mt-3" for="password-input">Password</label>
        <input id="password-input" name="password"
               :class="{'login-input form-control': true, 'is-invalid': v$.password.$error}"
               type="password" v-model.trim="v$.password.$model">
        <div class="invalid-feedback" v-for="error in v$.password.$errors" :key="error">
          {{ error.$message }}
        </div>
      </div>
    </div>
    <div class="link-div mt-3 d-flex flex-column">
      <p>No account yet?
        <router-link :to="{name: 'Register'}">Register</router-link>
      </p>
      <button class="btn btn-success w-50 align-self-center" :disabled="v$.$invalid">Log in</button>
      <span class="text-danger align-self-center">{{ message }}</span>
    </div>
  </form>
</template>

<script>
import {login} from '/src/api/auth';
import useVuelidate from '@vuelidate/core'
import {loginSchema} from "../../utils/validation/auth";
import {mapActions} from "vuex";

export default {
  setup: () => {
    return {v$: useVuelidate()}
  },
  name: "Login",
  data: () => ({
    username: "",
    password: "",
    message: ""
  }),
  validations: () => (loginSchema),
  methods: {
    async login() {
      const data = JSON.stringify({
        username: this.username,
        password: this.password
      });
      try {
        const response = await login(data);
        this.$cookies.set("token", response.token);
        await this.refreshUser(this.$cookies.get("token"));
        await this.$router.push({name: "Home"});
      } catch (error) {
        if (error.status === 401) {
          this.message = "Incorrect username or password";
        } else {
          this.message = "Something went wrong";
        }
      }
    },
    ...mapActions([
        "refreshUser"
    ])
  }
}
</script>
